name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install npm dependencies
      run: npm install

    - name: Build assets
      run: npm run build

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install Composer dependencies
      run: composer install --no-dev

    - name: Create archive
      run: zip -r plugin-v${GITHUB_REF##*/}.zip .

    - name: Upload Release Asset
      uses: actions/upload-artifact@v2
      with:
        name: plugin-v${GITHUB_REF##*/}.zip
        path: plugin-v${GITHUB_REF##*/}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: plugin-v${GITHUB_REF##*/}.zip
        path: .

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        assets: plugin-v${GITHUB_REF##*/}.zip
